### PR TITLE
Added some style to sign in/up forms

### PR DESCRIPTION
**Pull request by rumama**
Sign up/in forms now look a little better

### CODE REVIEW

**Comment by rumama** [comment]
:-1: Don't merge this! 
Sign up has a bug! Tomorrow I'll try to fix it.

**Comment by rumama** [comment]
All is working apart from this issue #77.
Still haven't figure a way to solve this issue. 
The bug was already present before this pull-request, so we can merge this pull-request and try to fix the bug later.

**Comment by brunofbrito** [comment]
I added some remarks to #77 but we can fix that issue later.
Let's do it! :+1:

**Comment by rumama** [comment]
:+1:

**Comment by rumama** [comment]
fixed #77

**Pull request merged**
